version: "3.7"
services:
  avito-db:
    container_name: avitoDB
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=dinol
      - POSTGRES_DB=avitoDB
    ports:
      - "5432:5432"
  migration:
    depends_on:
      - avito-db
    build: ./migration
    image: avito/migrations
    container_name: migrations
    restart: on-failure
    ports:
      - 9000:9000

  server:
    depends_on:
      - avito-db
    restart: on-failure
    build: .
    image: avito/experement
    container_name: avito-server

    ports:
      - "8080:8080"

