version: "3.7"
services:
  experement-db:
    container_name: avitoDB
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=dinol
      - POSTGRES_DB=avitoDB
    ports:
      - "5432:5432"
  server:
    build: .
    image: avito/experement
    container_name: avito-server
    ports:
      - "8080:8080"
    command: ["go", "run", "cmd", "main.go"]

